// alerts
export const CREATE_ALERT = 'CREATE_ALERT'
export const LOAD_ALERTS = 'LOAD_ALERTS'

// errors
export const AUTH_ERROR = 'AUTH_ERROR'
export const USER_ERROR = 'USER_ERROR'

// user
export const USER_SIGNUP = 'USER_SIGNUP'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_DELETE = 'USER_DELETE'
export const USER_REAUTHENTICATE = 'USER_REAUTHENTICATE'
export const USER_IS_ACTIVE = 'USER_IS_ACTIVE'
export const USER_FAKE = 'USER_FAKE'
export const USER_DELETE_FIREBASE_ACCOUNT = 'USER_DELETE_FIREBASE_ACCOUNT'

export const ON_AUTH_STATE_CHANGE = 'ON_AUTH_STATE_CHANGE'
export const AUTO_SIGNIN = 'AUTO_SIGNIN'

export const PASSWORD_CONFIRM = 'PASSWORD_CONFIRM'
export const PASSWORD_RESET = 'PASSWORD_RESET'
export const PASSWORD_CONFIRM_RESET = 'PASSWORD_CONFIR_RESET'
export const PASSWORD_VERIFY_RESET_CODE = 'PASSWORD_VERIFY_RESET_CODE'

export const SEND_EMAIL_VERIFICATION = 'SEND_EMAIL_VERIFICATION'
export const APPLY_ACTION_CODE = 'APPLY_ACTION_CODE'
export const GET_CREDENTIAL = 'GET_CREDENTIAL'

export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
