// alerts
export const CREATE_ALERT = 'CREATE_ALERT'
export const LOAD_ALERTS = 'LOAD_ALERTS'

// errors
export const AUTH_ERROR = 'AUTH_ERROR'
export const USER_ERROR = 'USER_ERROR'

// localDataBase

export const CREATE_USER_LOCAL_DB = 'CREATE_USER_LOCAL_DB'
export const UPDATE_USER_EMAIL_LOCAL_DB = 'UPDATE_USER_EMAIL_LOCAL_DB' // TODO: revisar uso
export const UPDATE_USER_LOCAL_DB = 'UPDATE_USER_LOCAL_DB' // TODO: revisar uso
export const GET_USER_DATA_LOCAL_DB = 'GET_USER_DATA_LOCAL_DB'
export const REMOVE_USER_LOCAL_DB = 'REMOVE_USER_LOCAL_DB'

// location
export const GET_CURRENT_POSITION = 'GET_CURRENT_POSITION'
export const CURRENT_ADDRESS = 'CURRENT_ADDRESS'

// password
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const CONFIRM_RESET_PASSWORD = 'CONFIRM_RESET_PASSWORD'
export const VERIFY_RESET_PASSWORD_CODE = 'VERIFY_RESET_PASSWORD_CODE'

// shared
export const SET_PLATFORM = 'SET_PLATFORM'

// social
export const DISPATCH_SIGNUP = 'DISPATCH_SIGNUP'
export const SOCIAL_SIGNUP = 'SOCIAL_SIGNUP'

// user
export const SIGNUP_USER = 'SIGNUP_USER'
export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const DELETE_USER = 'DELETE_USER'
export const REAUTHENTICATE_USER = 'REAUTHENTICATE_USER'
export const IS_USER_ACTIVE = 'IS_USER_ACTIVE'
export const DELETE_FIREBASE_USER_ACCOUNT = 'DELETE_FIREBASE_USER_ACCOUNT'
export const UPDATED_USER_PROFILE = 'UPDATED_USER_PROFILE'
export const ON_AUTH_STATE_CHANGE = 'ON_AUTH_STATE_CHANGE'
export const AUTO_SIGN_IN = 'AUTO_SIGN_IN'

export const SEND_EMAIL_VERIFICATION = 'SEND_EMAIL_VERIFICATION'
export const APPLY_ACTION_CODE = 'APPLY_ACTION_CODE'
export const GET_CREDENTIAL = 'GET_CREDENTIAL'

export const TO_JSON = 'TO_JSON'

// userDb
export const CREATE_USER_DB = 'CREATE_USER_DB'
export const USER_NAME_DB = 'USER_NAME_DB'
export const UPDATE_USER_DB = 'UPDATE_USER_DB'
export const DELETE_USER_DB = 'DELETE_USER_DB'
